version: '3.3'
services:
  zerotier-one:
    image: bltavares/zerotier
    devices:
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv6.conf.all.forwarding=1
    network_mode: host
    volumes:
      - '/var/lib/zerotier-one:/var/lib/zerotier-one'
        


# docker run --device=/dev/net/tun      --net=host     --cap-add=NET_ADMIN      --cap-add=SYS_ADMIN     -v /var/lib/zerotier-one:/var/lib/zerotier-one     -n zerotier-one     -d bltavares/zerotier